<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SD05CBJ" failures="1" tests="1" name="TestNGDemo.SoftAssertDemo" time="17.583" errors="0" timestamp="2022-07-04T14:38:45 IST" skipped="0">
  <testcase classname="TestNGDemo.SoftAssertDemo" name="TestFacebook" time="17.583">
    <failure message="The following asserts failed:
	URL mismatched expected [https://www.facebook.com/45] but found [https://www.facebook.com/login/web/?privacy_mutation_token=eyJ0eXBlIjo1LCJjcmVhdGlvbl90aW1lIjoxNjU2OTI1NzEzfQ%3D%3D&amp;cuid=AYjQ-8_ImdkxFD6Sc4X04067MT4iQPPU_zPSfMn2Dspp9nShwoS8AoH8rSZB7LSzEVViK7toYyW9e7HwSvvB1EiEsWERhjxRs2azZ63CeJhFBsh0-mnV8wgD1XL6CKohB2cUEywM4HUzwFh9l2aRuscwwtGg-jonL2BOGxORrF-wWuCtUlCU1NP35sorpXMEFTs&amp;email=H%20Y%20R%20Tutorials&amp;login_source=assistive_login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
URL mismatched expected [https://www.facebook.com/45] but found [https://www.facebook.com/login/web/?privacy_mutation_token=eyJ0eXBlIjo1LCJjcmVhdGlvbl90aW1lIjoxNjU2OTI1NzEzfQ%3D%3D&cuid=AYjQ-8_ImdkxFD6Sc4X04067MT4iQPPU_zPSfMn2Dspp9nShwoS8AoH8rSZB7LSzEVViK7toYyW9e7HwSvvB1EiEsWERhjxRs2azZ63CeJhFBsh0-mnV8wgD1XL6CKohB2cUEywM4HUzwFh9l2aRuscwwtGg-jonL2BOGxORrF-wWuCtUlCU1NP35sorpXMEFTs&email=H%20Y%20R%20Tutorials&login_source=assistive_login]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestNGDemo.SoftAssertDemo.TestFacebook(SoftAssertDemo.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestFacebook -->
  <system-out/>
</testsuite> <!-- TestNGDemo.SoftAssertDemo -->
